sudo: false
services:
  - mysql
language: node_js
node_js:
  - '8'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
install:
  - npm install
script:
  - npm run test
